version: "3.7"

services:
  core-serve:
    container_name: core-serve
    image: core-serve
    environment:
      - REGION=xxx
      - ACCESS_KEY_ID=xxx
      - ACCESS_KEY_SECRET=xxx
      - BUCKET=xxx
    networks:
      - proxy

networks:
  proxy:
    external: true
